- name: Create Bastion Host
  hosts: localhost
  gather_facts: no
  connection: local
  vars:

  tasks:
    - name: Launch instances
      gce:
          instance_names: "{{ instance_names }}"
          zone: "{{ zone_name }}"
          machine_type: "{{ machine_type }}"
          image: "{{ image }}"
          service_account_email: "{{ service_account_email }}"
          credentials_file: "{{ credentials_file }}"
          project_id: "{{ project_id }}"
          tags: bastion
          service_account_permissions: 
      register: gce
      ignore_errors: yes

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=60
      loop: "{{ gce.instance_data }}"

    - name: Add host to groupname
      add_host: hostname={{ item.public_ip }} groupname=new_instances
      loop: "{{ gce.instance_data }}"

    - gcdns_record:
        record: "{{ instance_names }}.{{ dns_zone }}"
        zone: "{{ dns_zone }}"
        type: A
        value: "{{ item.public_ip }}"
        overwrite: true 
        ttl: 5
      loop: "{{ gce.instance_data }}"

- name: Manage new instances
  hosts: new_instances
  connection: ssh
  sudo: True
 # roles:
 #   - base_configuration
 #  - production_server
  tasks:
    - name: Install base packages
      yum: name={{ item }} state=installed
      with_items:
        - subscription-manager
        - ansible
        - mlocate
        - python27-python-pip
        - git
        - python-libcloud 
        - qemu-img
        - wget
        - bind-utils
      tags:
        - packages
      ignore_errors: yes

    - name: Creates Galaxy directory
      file:
        path: "~/roles/"
        state: directory
        owner: awx
        group: awx
        mode: 0775

    - name: Enable new Galaxy file
      file:
        path: "~/roles/requirements.yml"
        state: touch
        mode: 0660
        owner: awx

    - name: Ansible create file with content example
      copy:
        dest: "~/roles/requirements.yml"
        content: |
          #Install a role from the Ansible Galaxy
          - src: wtanaka.gcloud-sdk    

    - name: Install Gcloud
      command: ansible-galaxy install -r ~/roles/requirements.yml -p ./roles/ --force
      register: ansible-galaxy
      roles:
         - role: wtanaka.gcloud-sdk

    - name: Install PIP
      command: easy_install pip
      register: pip-install

    - name: Install Ansible Tower CLI
      command: pip install ansible-tower-cli
      register: ansible-tower-cli

    - name: Install Apache Libcloud
      command: pip install apache-libcloud
      register: apache-libcloud

